src/character/urls.py
from django.urls import path

from character import views

app_name = "character"
urlpatterns = [
    path("", views.characters_list, name="list"),
    path("create/", views.character_create, name="create"),
    path("<int:pk>/", views.character_view, name="view"),
    path("<int:pk>/change/", views.character_change, name="change"),
    path("<int:pk>/delete/", views.character_delete, name="delete"),
    path(
        "<int:pk>/health_change/",
        views.character_health_change,
        name="health_change",
    ),
    path("<int:pk>/mana_change/", views.character_mana_change, name="mana_change"),
    path(
        "<int:pk>/recovery_points_change/",
        views.character_recovery_points_change,
        name="recovery_points_change",
    ),
    path(
        "<int:pk>/luck_points_change/",
        views.character_luck_points_change,
        name="luck_points_change",
    ),
    path("<int:pk>/notes_change/", views.character_notes_change, name="notes_change"),
    path(
        "<int:pk>/gm_notes_change/",
        views.character_gm_notes_change,
        name="gm_notes_change",
    ),
    path("<int:pk>/get_defense/", views.character_get_defense, name="get_defense"),
    path(
        "<int:pk>/defense_misc_change/",
        views.character_defense_misc_change,
        name="defense_misc_change",
    ),
    path(
        "<int:pk>/shield_change/",
        views.character_shield_change,
        name="shield_change",
    ),
    path(
        "<int:pk>/armor_change/",
        views.character_armor_change,
        name="armor_change",
    ),
    path(
        "<int:pk>/get_health_bar/",
        views.character_get_health_bar,
        name="get_health_bar",
    ),
    path(
        "<int:pk>/get_mana_bar/",
        views.character_get_mana_bar,
        name="get_mana_bar",
    ),
    path(
        "<int:pk>/get_initiative/",
        views.character_get_initiative,
        name="get_initiative",
    ),
    path(
        "<int:pk>/initiative_misc_change/",
        views.character_initiative_misc_change,
        name="initiative_misc_change",
    ),
    path(
        "<int:pk>/equipment_change/",
        views.character_equipment_change,
        name="equipment_change",
    ),
    path(
        "<int:pk>/damage_reduction_change/",
        views.character_damage_reduction_change,
        name="damage_reduction_change",
    ),
    path(
        "<int:character_pk>/add_next_in_path/<int:path_pk>/",
        views.add_next_in_path,
        name="add_next_in_path",
    ),
    path(
        "<int:character_pk>/remove_last_in_path/<int:path_pk>/",
        views.remove_last_in_path,
        name="remove_last_in_path",
    ),
    path("<int:pk>/add_path/", views.add_path, name="add_path"),
    path("<int:pk>/create_pet/", views.create_pet, name="create_pet"),
    path(
        "<int:pk>/remove_state/<int:state_pk>/",
        views.remove_state,
        name="remove_state",
    ),
    path("<int:pk>/add_state/<int:state_pk>/", views.add_state, name="add_state"),
    path("<int:pk>/reset_stats/", views.reset_stats, name="reset_stats"),
    path(
        "pet/<int:pk>/health_change/",
        views.pet_health_change,
        name="pet_health_change",
    ),
    path("pet/<int:pk>/change/", views.pet_change, name="pet_change"),
    path("pet/<int:pk>/delete/", views.pet_delete, name="pet_delete"),
]

src/charasheet/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import logout
from django.urls import include, path
from django_registration.backends.activation.views import RegistrationView

from common.forms import RegistrationForm
from common.views import hello_world

urlpatterns = [
    path("logout/", logout, {"next_page": settings.LOGOUT_REDIRECT_URL}, name="logout"),
    path(
        "accounts/register/",
        RegistrationView.as_view(form_class=RegistrationForm),
        name="django_registration_register",
    ),
    path("accounts/", include("django_registration.backends.activation.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("admin/", admin.site.urls),
    path("", hello_world, name="hello_world"),
    path("character/", include("character.urls", namespace="character")),
    path("party/", include("party.urls", namespace="party")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG_TOOLBAR:
    urlpatterns.insert(0, path("__debug__/", include("debug_toolbar.urls")))

if settings.DEBUG:
    urlpatterns.insert(0, path("__reload__/", include("django_browser_reload.urls")))

src/party/urls.py
from django.urls import path

from party import views

app_name = "party"
urlpatterns = [
    path("", views.parties_list, name="list"),
    path("create/", views.party_create, name="create"),
    path("<int:pk>/", views.party_details, name="details"),
    path("<int:pk>/change/", views.party_change, name="change"),
    path("<int:pk>/delete/", views.party_delete, name="delete"),
    path("<int:pk>/reset_stats/", views.party_reset_stats, name="reset_stats"),
    path("<int:pk>/add_effect/", views.party_add_effect, name="add_effect"),
    path(
        "<int:pk>/delete_effect/<int:effect_pk>/",
        views.party_delete_effect,
        name="delete_effect",
    ),
    path(
        "<int:pk>/increase_rounds/",
        views.party_increase_rounds,
        name="increase_rounds",
    ),
    path(
        "<int:pk>/decrease_rounds/",
        views.party_decrease_rounds,
        name="decrease_rounds",
    ),
    path("<int:pk>/leave/<int:character_pk>/", views.party_leave, name="leave"),
    path("<int:pk>/join/<int:character_pk>/", views.party_join, name="join"),
    path("<int:pk>/refuse/<int:character_pk>/", views.party_refuse, name="refuse"),
]

src/character/models/dice.py
from django.db import models


class Dice(models.IntegerChoices):
    D4 = 4
    D6 = 6
    D8 = 8
    D10 = 10
    D12 = 12
    D20 = 20

src/character/models/equipment.py
from django.db import models
from django_extensions.db.models import TimeStampedModel

from common.models import DocumentedModel, UniquelyNamedModel


class Weapon(  # noqa: DJ008
    UniquelyNamedModel,
    DocumentedModel,
    TimeStampedModel,
    models.Model,
):
    class Category(models.TextChoices):
        MELEE = "MEL", "corps à corps"
        RANGE = "RAN", "à distance"
        NONE = "NON", "aucune"

    damage = models.CharField(max_length=50, blank=True, verbose_name="dégâts")
    special = models.TextField(blank=True, verbose_name="spécial")
    category = models.CharField(
        max_length=3,
        choices=Category.choices,
        default=Category.NONE,
    )

    class Meta(UniquelyNamedModel.Meta, TimeStampedModel.Meta):
        verbose_name = "Arme"
        verbose_name_plural = "Armes"

src/character/models/utils.py
import functools


def cache_on_instance():
    def wrapper(func):
        @functools.wraps(func)
        def inner(self, arg):
            cache_name = func.__name__
            if (cached := _get_cache_value(self, cache_name, arg)) is not None:
                return cached
            res = func(self, arg)
            _set_cache_value(self, cache_name, arg, res)
            return res

        return inner

    return wrapper


def _get_cache_value(obj, cache_name: str, key: str) -> any:
    cache_name += "_cache"
    cache = getattr(obj, cache_name, None)
    if cache is None:
        cache = {}
        setattr(obj, cache_name, cache)
        return None

    return cache.get(key)


def _set_cache_value(obj, cache_name: str, key: str, value: any):
    cache_name += "_cache"
    cache = getattr(obj, cache_name)
    if cache is None:
        cache = {}
        setattr(obj, cache_name, cache)

    cache[key] = value

src/character/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, redirect, render
from django_htmx.http import trigger_client_event

from character.forms import AddPathForm, CharacterForm, EquipmentForm, PetForm
from character.models import Capability, Character, HarmfulState, Path
from character.models.pet import Pet
from character.templatetags.character_extras import modifier
from party.models import Party


@login_required
def characters_list(request):
    context = {
        "characters": Character.objects.owned_by(request.user).select_related(
            "race",
            "profile",
        ),
        "all_states": HarmfulState.objects.all(),
    }
    return render(request, "character/characters_list.html", context)


@login_required
def character_create(request):
    if request.method == "POST":
        form = CharacterForm(request.POST, request.FILES)
        if form.is_valid():
            character = form.save(commit=False)
            character.player = request.user
            character.recovery_points_remaining = character.recovery_points_max
            character.luck_points_remaining = character.luck_points_max
            character.mana_remaining = character.mana_max
            character.health_remaining = character.health_max
            character.save()
            form.save_m2m()
            messages.success(request, f"{character.name} a été créé.")
            return redirect("character:list")
    else:
        form = CharacterForm()
    context = {"form": form}
    return render(request, "character/character_form.html", context)


@login_required
def character_change(request, pk: int):
    character = get_object_or_404(Character.objects.managed_by(request.user), pk=pk)
    if request.method == "POST":
        form = CharacterForm(request.POST, request.FILES, instance=character)
        if form.is_valid():
            character = form.save()
            messages.success(request, f"{character.name} a été enregistré.")
            return redirect(character.get_absolute_url())
    else:
        form = CharacterForm(instance=character)
    context = {"form": form}
    return render(request, "character/character_form.html", context)


@login_required
def character_delete(request, pk: int):
    character = get_object_or_404(Character.objects.owned_by(request.user), pk=pk)
    context = {"character": character}
    if request.method == "POST":
        name = character.name
        character.delete()
        messages.success(request, f"Le personnage {name} a été supprimé.")
        return redirect("character:list")
    return render(request, "character/character_delete.html", context)


@login_required
def character_view(request, pk: int):
    character = get_object_or_404(
        Character.objects.friendly_to(request.user)
        .select_related("player", "racial_capability", "profile", "race")
        .prefetch_related("capabilities__path", "weapons"),
        pk=pk,
    )
    add_path_form = AddPathForm(character)
    context = {
        "character": character,
        "add_path_form": add_path_form,
        "all_states": HarmfulState.objects.all(),
    }
    party_pk = request.GET.get("party")
    if party_pk:
        context["party"] = get_object_or_404(
            Party.objects.related_to(request.user).prefetch_related("characters"),
            pk=party_pk,
        )
    return render(request, "character/character_details.html", context)


@login_required
def add_path(request, pk: int):
    character = get_object_or_404(Character.objects.managed_by(request.user), pk=pk)
    form = AddPathForm(character, request.POST)
    context = {"character": character}
    if form.is_valid():
        path: Path = form.cleaned_data.get("character_path") or form.cleaned_data.get(
            "other_path",
        )
        character.paths.add(path)
        context["add_path_form"] = AddPathForm(character)
    else:
        context["add_path_form"] = form
    return render(
        request,
        "character/snippets/character_details/paths_and_capabilities.html",
        context,
    )


@login_required
def character_health_change(request, pk: int):
    character = get_object_or_404(
        Character.objects.managed_by(request.user).only(
            "health_max",
            "health_remaining",
        ),
        pk=pk,
    )
    value = post_updated_value(
        request,
        character.health_remaining,
        character.health_max,
    )
    character.health_remaining = value
    character.save(update_fields=["health_remaining"])
    response = HttpResponse(value)
    return trigger_client_event(response, "refresh_health_bar")


@login_required
def character_mana_change(request, pk: int):
    character = get_object_or_404(
        Character.objects.managed_by(request.user)
        .only("mana_remaining", "level", "value_intelligence", "profile")
        .select_related("profile"),
        pk=pk,
    )
    value = get_updated_value(request, character.mana_remaining, character.mana_max)
    character.mana_remaining = value
    character.save(update_fields=["mana_remaining"])
    response = HttpResponse(value)
    return trigger_client_event(response, "refresh_mana_bar")


@login_required
def character_recovery_points_change(request, pk: int):
    character = get_object_or_404(
        Character.objects.managed_by(request.user).only("recovery_points_remaining"),
        pk=pk,
    )
    value = get_updated_value(
        request,
        character.recovery_points_remaining,
        character.recovery_points_max,
    )
    character.recovery_points_remaining = value
    character.save(update_fields=["recovery_points_remaining"])
    return HttpResponse(value)


@login_required
def character_defense_misc_change(request, pk: int):
    character = get_object_or_404(
        Character.objects.managed_by(request.user).only("defense_misc"),
        pk=pk,
    )
    value = get_updated_value(request, character.defense_misc, float("inf"))
    character.defense_misc = value
    character.save(update_fields=["defense_misc"])
    response = HttpResponse(value)
    return trigger_client_event(response, "update_defense")


@login_required
def character_shield_change(request, pk: int):
    character = get_object_or_404(
        Character.objects.managed_by(request.user).only("shield"),
        pk=pk,
    )
    value = get_updated_value(request, character.shield, float("inf"))
    character.shield = value
    character.save(update_fields=["shield"])
    response = HttpResponse(value)
    return trigger_client_event(response, "update_defense")


@login_required
def character_armor_change(request, pk: int):
    character = get_object_or_404(
        Character.objects.managed_by(request.user).only("armor"),
        pk=pk,
    )
    value = get_updated_value(request, character.armor, float("inf"))
    character.armor = value
    character.save(update_fields=["armor"])
    response = HttpResponse(value)
    return trigger_client_event(response, "update_defense")


@login_required
def character_initiative_misc_change(request, pk: int):
    character = get_object_or_404(
        Character.objects.managed_by(request.user).only("initiative_misc"),
        pk=pk,
    )
    value = get_updated_value(request, character.initiative_misc, float("inf"))
    character.initiative_misc = value
    character.save(update_fields=["initiative_misc"])
    response = HttpResponse(value)
    return trigger_client_event(response, "update_initiative")


@login_required
def character_luck_points_change(request, pk: int):
    character = get_object_or_404(
        Character.objects.managed_by(request.user).only(
            "luck_points_remaining",
            "value_charisma",
        ),
        pk=pk,
    )
    value = get_updated_value(
        request,
        character.luck_points_remaining,
        character.luck_points_max,
    )
    character.luck_points_remaining = value
    character.save(update_fields=["luck_points_remaining"])
    return HttpResponse(value)


def post_updated_value(
    request,
    remaining_value: float,
    max_value: float,
) -> int:
    action = request.POST.get("action")
    if action == "ko":
        return 0
    if action == "max":
        return int(max_value)

    multiplier = 0
    if action == "positive":
        multiplier = 1
    elif action == "negative":
        multiplier = -1

    form_value = int(request.POST.get("value"))
    remaining_value += form_value * multiplier
    remaining_value = min([max_value, remaining_value])
    remaining_value = max([0, remaining_value])

    return int(remaining_value)


def get_updated_value(
    request,
    remaining_value: float,
    max_value: float,
) -> int:
    form_value = request.GET.get("value")
    if form_value == "ko":
        remaining_value = 0
    elif form_value == "max":
        remaining_value = max_value
    else:
        form_value = int(form_value)
        remaining_value += form_value
        remaining_value = min([max_value, remaining_value])
        remaining_value = max([0, remaining_value])
    return int(remaining_value)


@login_required
def character_get_defense(request, pk: int):
    character = get_object_or_404(
        Character.objects.managed_by(request.user).only(
            "defense_misc",
            "armor",
            "shield",
            "value_dexterity",
        ),
        pk=pk,
    )
    return HttpResponse(character.defense)


@login_required
def character_get_health_bar(request, pk: int):
    character = get_object_or_404(
        Character.objects.managed_by(request.user).only(
            "health_max",
            "health_remaining",
        ),
        pk=pk,
    )
    context = {"character": character}
    return render(
        request,
        "character/snippets/character_details/health_bar.html",
        context,
    )


@login_required
def character_get_mana_bar(request, pk: int):

src/character/templates/character/snippets/characters_list/character_card.html
{% load character_extras %}
<div class="col">
    <div class="card character" data-id="{{ character.pk }}">
        <div class="card-body">
            <h5 class="card-title">
                {% if character.profile_picture %}
                    <img src="{{ character.profile_picture.url }}"
                         class="profile-pic-small rounded-5"
                         alt="Image de profil"
                    >
                {% endif %}
                {% if character.private %}
                    <i class="fa-solid fa-lock"
                       data-bs-toggle="tooltip"
                       data-bs-placement="top"
                       data-bs-title="Personnage privé, ne peut pas être invité dans un nouveau groupe."
                    ></i>
                {% endif %}
                {{ character.name }}
            </h5>
            <p class="card-text">
                {{ character.race.name }} {{ character.profile.name }} niv. {{ character.level }}<br>
                <span data-bs-toggle="tooltip" data-bs-placement="top" data-bs-title="Attaque au contact">
                    ⚔️&nbsp;{{ character.attack_melee|modifier }}
                </span> /
                <span data-bs-toggle="tooltip" data-bs-placement="top" data-bs-title="Attaque à distance">
                    🏹&nbsp;{{ character.attack_range|modifier }}
                </span> /
                <span data-bs-toggle="tooltip" data-bs-placement="top" data-bs-title="Attaque magique">
                    🪄&nbsp;{{ character.attack_magic|modifier }}
                </span> /
                <span data-bs-toggle="tooltip" data-bs-placement="top" data-bs-title="DEF">
                    🛡️&nbsp;{{ character.defense }}
                </span><br>
                <span data-bs-toggle="tooltip" data-bs-placement="top" data-bs-title="Initiative">
                    🎲&nbsp;{{ character.modifier_initiative|modifier }}
                </span> /
                <span data-bs-toggle="tooltip" data-bs-placement="top" data-bs-title="Mod. FOR">
                    💪&nbsp;{{ character.modifier_strength|modifier }}
                </span>
            </p>
            {% include "character/snippets/character_details/health_bar.html" %}
            {% if character.mana_max > 0 %}
                <div class="mt-1">
                    {% include "character/snippets/character_details/mana_bar.html" %}
                </div>
            {% endif %}
            <p class="card-text mt-3">
                {% with character.states.all as character_states %}
                    {% for state in all_states %}
                        <img src="{{ state.icon_url }}" alt="{{ state.name }}" height="25" width="25"
                             data-bs-toggle="tooltip"
                             data-bs-placement="top"
                             data-bs-title="{{ state.name }} : {{ state.description }}"
                             {% if state in character_states %}
                                 class="state-enabled"
                             {% endif %}
                        >
                    {% endfor %}
                {% endwith %}
            </p>
            <div class="btn-group btn-group-sm">
                {% if character.player == user %}
                    <a href="{% url "character:view" pk=character.pk %}{% if party %}?party={{ party.pk }}{% endif %}" class="btn btn-success">
                        <i class="fa-solid fa-user"></i> Jouer
                    </a>
                    {% if party %}
                        {% if character in party.characters.all %}
                            <a href="{% url "party:leave" pk=party.pk character_pk=character.pk %}" class="btn btn-warning">
                                <i class="fa-solid fa-person-walking-arrow-right"></i> Quitter le groupe
                            </a>
                        {% elif character in party.invited_characters.all %}
                            <a href="{% url "party:join" pk=party.pk character_pk=character.pk %}" class="btn btn-primary">
                                <i class="fa-solid fa-check"></i> Rejoindre
                            </a>
                            <a href="{% url "party:refuse" pk=party.pk character_pk=character.pk %}" class="btn btn-warning">
                                <i class="fa-solid fa-person-walking-arrow-right"></i> Refuser l'invitation
                            </a>
                        {% endif %}
                    {% else %}
                        <a href="{% url "character:delete" pk=character.pk %}" class="btn btn-danger delete">
                            <i class="fa-solid fa-user-minus"></i> Supprimer
                        </a>
                    {% endif %}
                {% elif character|managed_by:user %}
                    <a href="{% url "character:view" pk=character.pk %}{% if party %}?party={{ party.pk }}{% endif %}" class="btn btn-primary manage">
                        <i class="fa-solid fa-cog"></i> Gérer
                    </a>
                {% else %}
                    <a href="{% url "character:view" pk=character.pk %}{% if party %}?party={{ party.pk }}{% endif %}" class="btn btn-primary observe">
                        <i class="fa-solid fa-eye"></i> Observer
                    </a>
                {% endif %}
            </div>
        </div>
    </div>
</div>

src/character/templates/character/snippets/characters_list/pet_card.html
{% load character_extras %}
<div class="col">
    <div class="card pet" data-id="{{ pet.pk }}">
        <div class="card-body">
            <h5 class="card-title pet-name">
                {{ pet.name }}
            </h5>
            <p class="card-text">
                <span data-bs-toggle="tooltip" data-bs-placement="top" data-bs-title="Attaque">
                    ⚔️&nbsp;{{ pet.attack }}
                </span> /
                <span data-bs-toggle="tooltip" data-bs-placement="top" data-bs-title="DEF">
                    🛡️&nbsp;{{ pet.defense }}
                </span> /
                <span data-bs-toggle="tooltip" data-bs-placement="top" data-bs-title="Initiative">
                    🎲&nbsp;{{ pet.initiative }}
                </span>
            </p>
            <div class="health">
                {% include "character/snippets/character_details/pet_health_bar.html" %}
                {% if pet.owner|managed_by:user %}
                    <div class="btn-group btn-group-sm mt-1" role="group">
                        <button
                            hx-get="{% url "character:pet_health_change" pk=pet.pk %}?value=ko"
                            hx-target='[data-id="{{ pet.pk }}"] .health .progress'
                            hx-swap="outerHTML"
                            type="button"
                            class="btn btn-outline-danger min"><i class="fa-solid fa-battery-empty"></i></button>
                        <button
                            hx-get="{% url "character:pet_health_change" pk=pet.pk %}?value=-1"
                            hx-target='[data-id="{{ pet.pk }}"] .health .progress'
                            hx-swap="outerHTML"
                            type="button"
                            class="btn btn-danger decrease"><i class="fa-solid fa-minus"></i></button>
                        <button
                            hx-get="{% url "character:pet_health_change" pk=pet.pk %}?value=1"
                            hx-target='[data-id="{{ pet.pk }}"] .health .progress'
                            hx-swap="outerHTML"
                            type="button"
                            class="btn btn-success increase"><i class="fa-solid fa-plus"></i></button>
                        <button
                            hx-get="{% url "character:pet_health_change" pk=pet.pk %}?value=max"
                            hx-target='[data-id="{{ pet.pk }}"] .health .progress'
                            hx-swap="outerHTML"
                            type="button"
                            class="btn btn-outline-success max"><i class="fa-solid fa-battery-full"></i></button>
                    </div>
                {% endif %}
            </div>
            {% if pet.owner|managed_by:user %}
                <a href="{% url "character:pet_change" pk=pet.pk %}"
                   class="edit">Modifier</a>
            {% endif %}
            {% if pet.owner|owned_by:user %}
                <a href="{% url "character:pet_delete" pk=pet.pk %}"
                   class="delete">Supprimer</a>
            {% endif %}
        </div>
    </div>
</div>