src/charasheet/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import logout
from django.urls import include, path
from django_registration.backends.activation.views import RegistrationView

from common.forms import RegistrationForm
from common.views import hello_world

urlpatterns = [
    path("logout/", logout, {"next_page": settings.LOGOUT_REDIRECT_URL}, name="logout"),
    path(
        "accounts/register/",
        RegistrationView.as_view(form_class=RegistrationForm),
        name="django_registration_register",
    ),
    path("accounts/", include("django_registration.backends.activation.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("admin/", admin.site.urls),
    path("", hello_world, name="hello_world"),
    path("character/", include("character.urls", namespace="character")),
    path("party/", include("party.urls", namespace="party")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG_TOOLBAR:
    urlpatterns.insert(0, path("__debug__/", include("debug_toolbar.urls")))

if settings.DEBUG:
    urlpatterns.insert(0, path("__reload__/", include("django_browser_reload.urls")))

src/party/urls.py
from django.urls import path

from party import views

app_name = "party"
urlpatterns = [
    path("", views.parties_list, name="list"),
    path("create/", views.party_create, name="create"),
    path("<int:pk>/", views.party_details, name="details"),
    path("<int:pk>/change/", views.party_change, name="change"),
    path("<int:pk>/delete/", views.party_delete, name="delete"),
    path("<int:pk>/reset_stats/", views.party_reset_stats, name="reset_stats"),
    path("<int:pk>/add_effect/", views.party_add_effect, name="add_effect"),
    path(
        "<int:pk>/delete_effect/<int:effect_pk>/",
        views.party_delete_effect,
        name="delete_effect",
    ),
    path(
        "<int:pk>/increase_rounds/",
        views.party_increase_rounds,
        name="increase_rounds",
    ),
    path(
        "<int:pk>/decrease_rounds/",
        views.party_decrease_rounds,
        name="decrease_rounds",
    ),
    path("<int:pk>/leave/<int:character_pk>/", views.party_leave, name="leave"),
    path("<int:pk>/join/<int:character_pk>/", views.party_join, name="join"),
    path("<int:pk>/refuse/<int:character_pk>/", views.party_refuse, name="refuse"),
]

src/party/models.py
from django.db import models
from django.db.models import F, Q
from django.urls import reverse
from django_extensions.db.models import TimeStampedModel

from character.models import Character
from common.models import UniquelyNamedModel, UniquelyNamedModelManager


class PartyQuerySet(models.QuerySet):
    def managed_by(self, user):
        return self.filter(game_master=user)

    def played_by(self, user):
        return self.filter(characters__in=Character.objects.filter(player=user))

    def played_or_mastered_by(self, user):
        return self.filter(
            Q(game_master=user)
            | Q(characters__in=Character.objects.filter(player=user)),
        ).distinct()

    def related_to(self, user):
        return self.filter(
            Q(game_master=user)
            | Q(characters__in=Character.objects.filter(player=user))
            | Q(invited_characters__in=Character.objects.filter(player=user)),
        ).distinct()

    def invited_to(self, user):
        return self.filter(invited_characters__in=Character.objects.filter(player=user))


class PartyManager(UniquelyNamedModelManager):
    pass


class Party(UniquelyNamedModel, TimeStampedModel, models.Model):  # noqa: DJ008
    game_master = models.ForeignKey(
        "common.User",
        on_delete=models.PROTECT,
        related_name="parties",
        verbose_name="meneur de jeu",
    )
    invited_characters = models.ManyToManyField(
        "character.Character",
        blank=True,
        related_name="invites",
        verbose_name="personnages invités",
    )
    characters = models.ManyToManyField(
        "character.Character",
        blank=True,
        related_name="parties",
        verbose_name="personnages",
    )

    objects = PartyManager.from_queryset(PartyQuerySet)()

    class Meta(UniquelyNamedModel.Meta, TimeStampedModel.Meta):
        verbose_name = "Groupe"
        verbose_name_plural = "Groupes"

    def get_absolute_url(self) -> str:
        return reverse("party:details", kwargs={"pk": self.pk})

    def reset_stats(self):
        for character in self.characters.all():
            character.reset_stats()


class BattleEffectQuerySet(models.QuerySet):
    def increase_rounds(self):
        self.temporary().update(remaining_rounds=F("remaining_rounds") + 1)

    def decrease_rounds(self):
        self.active().update(remaining_rounds=F("remaining_rounds") - 1)

    def active(self):
        return self.filter(remaining_rounds__gt=0)

    def terminated(self):
        return self.filter(remaining_rounds=0)

    def permanent(self):
        return self.filter(remaining_rounds=-1)

    def temporary(self):
        return self.exclude(remaining_rounds=-1)


class BattleEffectManager(models.Manager):
    pass


class BattleEffect(TimeStampedModel, models.Model):
    name = models.CharField(max_length=100, blank=False, null=False, verbose_name="nom")
    target = models.CharField(
        max_length=100,
        blank=False,
        null=False,
        verbose_name="cible",
    )
    description = models.TextField(blank=True, null=False, verbose_name="description")
    remaining_rounds = models.SmallIntegerField(
        blank=False,
        default=-1,
        verbose_name="nombre de tours restants",
        help_text="-1 pour un effet permanent",
    )
    party = models.ForeignKey(
        "party.Party",
        on_delete=models.CASCADE,
        related_name="effects",
        verbose_name="groupe",
    )
    created_by = models.ForeignKey(
        "common.User",
        on_delete=models.CASCADE,
        related_name="effects",
        verbose_name="créé par",
    )

    objects = BattleEffectManager.from_queryset(BattleEffectQuerySet)()

    def __str__(self):
        return self.name

    @property
    def remaining_percent(self) -> float:
        max_display_percent = 5
        if self.remaining_rounds >= max_display_percent or self.remaining_rounds < 0:
            return 100
        return self.remaining_rounds / max_display_percent * 100

src/party/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.db.models import Q

from character.models import Character
from party.models import BattleEffect, Party


class PartyForm(forms.ModelForm):
    def __init__(self, *args, **kwargs) -> None:
        self.original_instance = kwargs.get("instance")
        super().__init__(*args, **kwargs)
        qs = Character.objects.all()
        if self.original_instance:
            qs = qs.filter(
                Q(private=False)
                | Q(
                    pk__in=self.original_instance.invited_characters.all().values_list(
                        "pk",
                        flat=True,
                    ),
                ),
            )
        self.fields["invited_characters"].queryset = qs

    class Meta:
        model = Party
        fields = ["name", "invited_characters"]

    def clean_invited_characters(self):
        invited = self.cleaned_data["invited_characters"]
        if not self.original_instance:
            return invited
        members = self.original_instance.characters.all()
        for character in invited:
            if character in members:
                self.add_error(
                    "invited_characters",
                    ValidationError(f"{character} is already a group member."),
                )
        return invited


class BattleEffectForm(forms.ModelForm):
    class Meta:
        model = BattleEffect
        fields = ["name", "target", "description", "remaining_rounds"]

src/party/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect, render
from django.views.decorators.http import require_GET, require_http_methods

from character.models import Character, HarmfulState
from party.forms import BattleEffectForm, PartyForm
from party.models import BattleEffect, Party


@require_GET
@login_required
def parties_list(request):
    context = {
        "managed_parties": Party.objects.managed_by(request.user),
        "played_parties": Party.objects.played_by(request.user).distinct(),
        "invited_to": Party.objects.invited_to(request.user).distinct(),
    }
    return render(request, "party/parties_list.html", context)


@require_http_methods(["GET", "POST"])
@login_required
def party_create(request):
    if request.method == "GET":
        form = PartyForm()
    else:
        form = PartyForm(request.POST)
        if form.is_valid():
            party = form.save(commit=False)
            party.game_master = request.user
            party.save()
            form.save_m2m()
            return redirect("party:list")
    context = {"form": form}
    return render(request, "party/party_form.html", context)


@require_GET
@login_required
def party_details(request, pk):
    party = get_object_or_404(Party.objects.related_to(request.user), pk=pk)
    context = {
        "party": party,
        "all_states": HarmfulState.objects.all(),
    }
    return render(request, "party/party_details.html", context)


@require_http_methods(["GET", "POST"])
@login_required
def party_delete(request, pk):
    party = get_object_or_404(Party.objects.managed_by(request.user), pk=pk)
    context = {"party": party}
    if request.method == "POST":
        name = party.name
        party.delete()
        messages.success(request, f"Le groupe {name} a été supprimé.")
        return redirect("party:list")
    return render(request, "party/party_delete.html", context)


@require_http_methods(["GET", "POST"])
@login_required
def party_reset_stats(request, pk):
    party = get_object_or_404(Party.objects.managed_by(request.user), pk=pk)
    context = {"party": party}
    if request.method == "POST":
        name = party.name
        party.reset_stats()
        message = f"Les stats de tous les membres de {name} ont été réinitialisées."
        messages.success(request, message)
        return redirect(party)
    return render(request, "party/party_reset_stats.html", context)


@require_http_methods(["GET", "POST"])
@login_required
def party_add_effect(request, pk):
    party = get_object_or_404(Party.objects.played_or_mastered_by(request.user), pk=pk)
    context = {"party": party}
    if request.method == "GET":
        form = BattleEffectForm()
    else:
        form = BattleEffectForm(request.POST or None)
        if form.is_valid():
            effect = form.save(commit=False)
            effect.party = party
            effect.created_by = request.user
            effect.save()
            return render(request, "party/snippets/effects.html", context)
    context["form"] = form
    return render(request, "party/snippets/add_effect_form.html", context)


@require_GET
@login_required
def party_increase_rounds(request, pk):
    party = get_object_or_404(Party.objects.played_or_mastered_by(request.user), pk=pk)
    party.effects.increase_rounds()
    return render(request, "party/snippets/effects.html", {"party": party})


@require_GET
@login_required
def party_decrease_rounds(request, pk):
    party = get_object_or_404(Party.objects.played_or_mastered_by(request.user), pk=pk)
    party.effects.decrease_rounds()
    return render(request, "party/snippets/effects.html", {"party": party})


@require_GET
@login_required
def party_delete_effect(request, pk, effect_pk):
    party = get_object_or_404(Party.objects.played_or_mastered_by(request.user), pk=pk)
    BattleEffect.objects.filter(pk=effect_pk).delete()
    return render(request, "party/snippets/effects.html", {"party": party})


@require_http_methods(["GET", "POST"])
@login_required
def party_change(request, pk):
    party = get_object_or_404(Party.objects.managed_by(request.user), pk=pk)
    context = {"party": party}
    if request.method == "GET":
        form = PartyForm(instance=party)
    else:
        form = PartyForm(request.POST or None, instance=party)
        if form.is_valid():
            form.save()
            messages.success(request, "Groupe modifié.")
            return redirect("party:list")
    context["form"] = form
    return render(request, "party/party_form.html", context)


@require_http_methods(["GET", "POST"])
@login_required
def party_leave(request, pk, character_pk):
    party = get_object_or_404(Party.objects.played_by(request.user).distinct(), pk=pk)
    character = get_object_or_404(
        Character.objects.owned_by(request.user),
        pk=character_pk,
    )
    context = {"party": party, "character": character}
    if request.method == "POST":
        character.parties.remove(party)
        messages.success(request, f"{character} a quitté le groupe {party}.")
        return redirect("party:list")
    return render(request, "party/party_leave.html", context)


@require_GET
@login_required
def party_join(request, pk, character_pk):
    party = get_object_or_404(Party.objects.invited_to(request.user).distinct(), pk=pk)
    character = get_object_or_404(
        Character.objects.owned_by(request.user),
        pk=character_pk,
    )
    party.characters.add(character)
    party.invited_characters.remove(character)
    messages.success(request, f"{character} a rejoint le groupe {party}.")
    return redirect("party:list")


@require_GET
@login_required
def party_refuse(request, pk, character_pk):
    party = get_object_or_404(Party.objects.invited_to(request.user).distinct(), pk=pk)
    character = get_object_or_404(
        Character.objects.owned_by(request.user),
        pk=character_pk,
    )
    party.invited_characters.remove(character)
    messages.success(request, f"{character} a refusé l'invitation au groupe {party}.")
    return redirect("party:list")

src/party/templates/party/parties_list.html
{% extends "common/base.html" %}
{% load character_extras %}

{% block title %}Groupes{% endblock %}

{% block content %}
    <h1>Groupes</h1>
    <a href="{% url "party:create" %}" class="btn btn-primary mb-3">
        <i class="fa-solid fa-user-plus"></i> Nouveau groupe
    </a>
    {% if managed_parties %}
        <h2>Groupes que vous gérez</h2>
        <div class="row row-cols-1 row-cols-md-2 row-cols-lg-3 g-4">
            {% for party in managed_parties %}
                <div class="col">
                    <div class="card party" data-id="{{ party.pk }}">
                        <div class="card-body">
                            <h5 class="card-title">
                                {{ party.name }}
                            </h5>
                            <div class="btn-group btn-group-sm">
                                <a href="{% url "party:details" pk=party.pk %}" class="btn btn-success access">
                                    <i class="fa-solid fa-users"></i> Accéder
                                </a>
                                <a href="{% url "party:change" pk=party.pk %}" class="btn btn-secondary edit">
                                    <i class="fa-solid fa-gear"></i> Modifier
                                </a>
                                <a href="{% url "party:delete" pk=party.pk %}" class="btn btn-danger delete">
                                    <i class="fa-solid fa-users-slash"></i> Supprimer
                                </a>
                            </div>

                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    {% endif %}
    {% if played_parties %}
        <h2 class="mt-3">Groupes dont vous êtes membre</h2>
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 row-cols-lg-4 g-4">
            {% for party in played_parties %}
                <div class="col">
                    <div class="card">
                        <div class="card-body">
                            <h5 class="card-title">
                                {{ party.name }}
                            </h5>
                            <a href="{% url "party:details" pk=party.pk %}" class="btn btn-sm btn-success">
                                <i class="fa-solid fa-users"></i> Accéder
                            </a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    {% endif %}
    {% if invited_to %}
        <h2 class="mt-3">Groupes auxquels vous avez été invités</h2>
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 row-cols-lg-4 g-4">
            {% for party in invited_to %}
                <div class="col">
                    <div class="card">
                        <div class="card-body">
                            <h5 class="card-title">
                                {{ party.name }}
                            </h5>
                            <a href="{% url "party:details" pk=party.pk %}" class="btn btn-sm btn-success">
                                <i class="fa-solid fa-users"></i> Accéder
                            </a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    {% endif %}
{% endblock %}

src/party/templates/party/party_delete.html
{% extends "common/base.html" %}
{% load character_extras %}

{% block title %}Suppression groupe {{ party.name }}{% endblock %}

{% block content %}
    <h1>Suppression groupe {{ party.name }}</h1>
    <form action="{% url "party:delete" pk=party.pk %}" method=post>
        {% csrf_token %}
        <p>
            Êtes-vous certain de vouloir supprimer le groupe {{ party.name }} ?<br>
            Cette action est irréversible.
        </p>
        <button class="btn btn-danger" type="submit">
            <i class="fa-solid fa-users-slash"></i> Supprimer le groupe
        </button>
    </form>
{% endblock %}

src/party/templates/party/party_details.html
{% extends "common/base.html" %}
{% load django_bootstrap5 %}
{% load character_extras %}

{% block title %}{{ party.name }} &centerdot; Groupe{% endblock %}

{% block content %}
    <h1>{{ party.name }}</h1>
    <p>MJ : {{ party.game_master.get_full_name|default:party.game_master.username }}</p>
    {% if party.game_master == request.user %}
        <p>
            <a href="{% url "party:reset_stats" pk=party.pk %}" id="reset-stats">Réinitialiser
                les stats</a>
        </p>
    {% endif %}
    <h2 class="mt-4">Personnages</h2>
    <div class="row row-cols-1 row-cols-md-2 row-cols-lg-3 row-cols-xl-4 g-4">
        {% for character in party.characters.all %}
            {% include "character/snippets/characters_list/character_card.html" %}
        {% empty %}
            <p>Aucun...</p>
        {% endfor %}
    </div>
    {% with party.invited_characters.all as invites %}
        {% if invites %}
            <h2 class="mt-4">Invités</h2>
            <div class="row row-cols-1 row-cols-md-2 row-cols-lg-3 row-cols-xl-4 g-4">
                {% for character in invites %}
                    {% include "character/snippets/characters_list/character_card.html" %}
                {% endfor %}
            </div>
        {% endif %}
    {% endwith %}
    <h2 class="mt-4">Combat</h2>
    {% include "party/snippets/effects.html" %}
{% endblock %}

src/party/templates/party/party_form.html
{% extends "common/base.html" %}
{% load django_bootstrap5 %}
{% load character_extras %}

{% block title %}Gérer un groupe{% endblock %}

{% block content %}
    <h1>Gérer un groupe</h1>
    <form action="" method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% bootstrap_button type="submit" content="Enregistrer" %}
    </form>
{% endblock %}

src/party/templates/party/party_leave.html
{% extends "common/base.html" %}
{% load character_extras %}

{% block title %}Quitter le groupe {{ party.name }}{% endblock %}

{% block content %}
    <h1>Quitter le groupe {{ party.name }}</h1>
    <form action="{% url "party:leave" pk=party.pk character_pk=character.pk %}" method=post>
        {% csrf_token %}
        <p>
            Êtes-vous certain de vouloir faire quitter le groupe {{ party.name }} à {{ character.name }} ?
        </p>
        <button class="btn btn-danger" type="submit">
            <i class="fa-solid fa-person-walking-arrow-right"></i> Quitter le groupe
        </button>
    </form>
{% endblock %}

src/party/templates/party/party_reset_stats.html
{% extends "common/base.html" %}

{% block title %}Réinitialisation des stats des membres de {{ party.name }}{% endblock %}

{% block content %}
    <h1>Réinitialisation des stats des membres de {{ party.name }}</h1>
    <form action="{% url "party:reset_stats" pk=party.pk %}" method=post>
        {% csrf_token %}
        <p>
            Êtes-vous certain de vouloir réinitialiser les stats de tous les membres de {{ party.name }} ?<br>
            Cette action est irréversible.
        </p>
        <p>Joueurs affectés :</p>
        <ul>
            {% for character in party.characters.all %}
                <li>{{ character.name }}</li>
            {% endfor %}
        </ul>
        {% include "character/snippets/reset_affected_stats.html" %}
        <button class="btn btn-primary" type="submit">
            <i class="fa-solid fa-suitcase-medical"></i> Réinitialiser les stats
        </button>
    </form>
{% endblock %}